### ISSUE TITLE
Declaration of module 'react' causing type conflicts

### ISSUE THREAD

**Issue by remLse** [plouc/nivo#1718]
I don't quite get what's going on here. The typescript compiler indicates, that this definition of `forwardRef` actually overwrites the regular definition for react. That causes type errors with my own code. Is this conflict happening, because I'm doing something wrong?

https://github.com/plouc/nivo/blob/928c443af49150e0ade2c825f747704f89771c38/packages/bar/src/BarCanvas.tsx#L39

After updating nivo from 0.70.1 to 0.73.0, I also get a ton of type conflicts similar to this one:

```
node_modules/@types/react-helmet/node_modules/@types/react/index.d.ts:3128:13 - error TS2717:
Subsequent property declarations must have the same type. 
Property 'label' must be of type 'DetailedHTMLProps<LabelHTMLAttributes<HTMLLabelElement>, HTMLLabelElement>',
but here has type 'DetailedHTMLProps<LabelHTMLAttributes<HTMLLabelElement>, HTMLLabelElement>'.

3128             label: React.DetailedHTMLProps<React.LabelHTMLAttributes<HTMLLabelElement>, HTMLLabelElement>;
                 ~~~~~

node_modules/@types/react/index.d.ts:3049:13
3049             label: React.DetailedHTMLProps<React.LabelHTMLAttributes<HTMLLabelElement>, HTMLLabelElement>;
                 ~~~~~
    'label' was also declared here.
```

There are almost 200 of these type conflicts, all of them between the type declarations of react and react-helmet. I assume this must have something to do with the first problem. However, simply uncommenting the lines where the module 'react' is declared in the nivo package actually fixes my first issue (conflict between own code and redeclaration of forwardRef in nivo), while the second remains (conflicts between react and react-helmet).

I hope someone can shed some light on this. Looking at my `yarn.lock` file, neither react nor react-helmet has changed after updating. The only non-nivo package that changed is `d3-time-format@2.3.0` (deleted, now using v3.0.0). It seems minor and unrelated.

**Comment by potty** [comment]
Any update about this issue please? We recently tried to update the lib to latest version, but forwardRef doesn't return Component type anymore. Is there any solution to this?

**Comment by plouc** [comment]
Fixed by https://github.com/plouc/nivo/pull/1793.
