### ISSUE TITLE
Line Chart Breaking with NextJS after upgrading to 0.65.1

### ISSUE THREAD

**Issue by p45mark** [plouc/nivo#1290]
**Describe/explain the bug**
The lines on my ResponsiveLine component are messed up after upgrading to version 0.65.1. Just to make sure, I downgraded to 0.64.0 and the ResponsiveLine components looked great again.

Console Error with static site hosted locally or on Vercel
```
TypeError: r.willAdvance is not a function
```

**To Reproduce**
The easiest way is to clone the repo below and try running `yarn prod` with each version of `@nivo/line` and you'll see the problems with `0.65.1` locally. I also have this hosted on Vercel (with version `0.65.1`).

[Broken version hosted on Vercel](https://next-nivo.vercel.app/)
[Github Repo](https://github.com/p45mark/next-nivo)
![image](https://user-images.githubusercontent.com/48729903/99325525-6352af00-282b-11eb-9a92-db1fb4aa9360.png)

Thanks!

**Comment by wyze** [comment]
We switched to react-spring v9 and it is an issue there. We won't be able to fix it until they release a new version. There are some workarounds you can try in your project. https://github.com/pmndrs/react-spring/issues/1078

**Comment by plouc** [comment]
@p45mark we also have this issue and we fixed it by using [this script](https://github.com/plouc/nivo/blob/master/scripts/patch-react-spring.js), it should be run prior to build.

**Comment by p45mark** [comment]
That fixed it for now, thank you both!

**Comment by wmcb91** [comment]
@p45mark @plouc 

I found an additional solution to work with Next 10.0.3 and the most recent Nivo release (^0.67.0). It will work for any folks who are having trouble running your provided prebuild script in their environments. You can fix the `TypeError: r.willAdvance is not a function` issue by adding this webpack config function to your **next.config.js** file:

```js
module.exports = {
  ...
  webpack: config => {
    config.module.rules.push({
      test: /react-spring/,
      sideEffects: true,
    })

    return config
  },
}
```

**Comment by tonirilix** [comment]
> @p45mark @plouc
> 
> I found an additional solution to work with Next 10.0.3 and the most recent Nivo release (^0.67.0). It will work for any folks who are having trouble running your provided prebuild script in their environments. You can fix the `TypeError: r.willAdvance is not a function` issue by adding this webpack config function to your **next.config.js** file:
> 
> ```js
> module.exports = {
>   ...
>   webpack: config => {
>     config.module.rules.push({
>       test: /react-spring/,
>       sideEffects: true,
>     })
> 
>     return config
>   },
> }
> ```

I can confirm this workaround fixed the error on my production build. Thx! 🎉

**Comment by markmiro** [comment]
This is the way to fix the `TypeError: r.willAdvance is not a function` in **Gatsby** (based on the answer for Next.js):
```
// gatsby-node.js
exports.onCreateWebpackConfig = ({
  stage,
  rules,
  loaders,
  plugins,
  actions,
}) => {
  actions.setWebpackConfig({
    module: {
      rules: [{
        test: /react-spring/,
        sideEffects: true,
      }]
    }
  })
};
```

Aside: I've also been able to reproduce the issue in a Create React App project.

**Comment by SirPm** [comment]
> This is the way to fix the `TypeError: r.willAdvance is not a function` in **Gatsby** (based on [the answer for Next.js](https://github.com/plouc/nivo/issues/1290#issuecomment-752280413)):
> 
> ```js
> // gatsby-node.js
> exports.onCreateWebpackConfig = ({
>   stage,
>   rules,
>   loaders,
>   plugins,
>   actions,
> }) => {
>   actions.setWebpackConfig({
>     module: {
>       rules: [{
>         test: /react-spring/,
>         sideEffects: true,
>       }]
>     }
>   })
> };
> ```
> 
> Repo here: https://github.com/markmiro/gatsby-nivo-chart-test
> 
> Aside: I've also been able to reproduce the issue in a Create React App project.

Hi, I'm experiencing this in a Create React App project and I don't know if downgrading to 0.62 will help because mine too only shows that error in production and its somehow affecting my styling in production

**Comment by jamesdh** [comment]
@plouc @wyze 9.x+ of react-spring are now published. I went ahead and created #1480 for upgrading it and hopefully putting this issue to rest.

**Comment by pietmichal** [comment]
My quick solution is to add 

```
"resolutions": {
  "react-spring": "9.0.1"
}
```

to package.json and run `yarn install`

**Comment by ashic** [comment]
> "resolutions": {
>   "react-spring": "9.0.1"
> }

I had a similar issue where scatterplot hover popups were not moving for production builds, but worked fine in dev. The react-spring resolution fixed it for me as well.
