### ISSUE TITLE
Error: Cannot find module '@nivo/core' after upgrading to 0.65.0

### ISSUE THREAD

**Issue by p45mark** [plouc/nivo#1286]
**Describe/explain the bug**
After upgrading the Pie and Line charts to version 0.65.0 I'm getting the error
`Module not found: Can't resolve '@nivo/core'`

**To Reproduce**
In this codesandbox just bump the version of `@nivo/pie` to `0.65.0` to see the error
https://codesandbox.io/s/nivo-core-required-zk09f?file=/src/App.js

1. Go here: https://codesandbox.io/s/nivo-core-required-zk09f?file=/src/App.js
2. Bump version to 0.65.0

**Desktop (please complete the following information):**
 - OS: Mac Catalina
 - Chrome 

**Additional context**
Maybe we just need to update the documentation if `@nivo/core` is required now

**Comment by orhels** [comment]
Had the same issue. Added `@nivo/core` as a dependency to fix it.

**Comment by wyze** [comment]
It is a peer dependency on all of the packages to prevent cyclical dependencies between core and tooltip. So like orhels mentions, you need to specify it in your dependencies now.

**Comment by wyze** [comment]
Yes, updating the documentation/readme would be a step in the right direction. :)

**Comment by orhels** [comment]
@wyze Note that the peer dependency is set to 0.64.0 for some of the packages. Checked the ones I use (annotations, axes, bar, colors, legends, pie and tooltip) and all has 0.64.0 as a peer dependency. When testing pie with core 0.64.0 in code sandbox the app crashes https://codesandbox.io/s/nivo-core-required-forked-gdd1x.

**Comment by wyze** [comment]
Yup, we need to fix that with lerna, it isn't bumping peer dependencies correctly.

**Comment by plouc** [comment]
It's been fixed with `0.65.1` for charts, which now point to `@nivo/core@0.65.0`.

**Comment by plouc** [comment]
We also added some install instructions in the generated code snippet on the website.

**Comment by matthewkwong2** [comment]
So just to make sure I get it right, we now have to explicitly specify `@nivo/core@^0.65.0` in `package.json` for `v0.65.x` (perhaps also in future versions)?

**Comment by wyze** [comment]
@matthewkwong2 Correct. You should bump @nivo/core dependency when you bump your other packages as well.

**Comment by matthewkwong2** [comment]
Well, I think you should really mention this in the release note (or maybe make it more obvious if it is mentioned somewhere). This is a breaking change.

**Comment by plouc** [comment]
@matthewkwong2, it is now indicated in the generated code snippet, also when you install, you'll get warnings about required versions.

**Comment by plouc** [comment]
This was already the case for a few package before the latest release, but the main difference is that the version defined in `peerDependencies` is now correct.

**Comment by arthuryeti** [comment]
@plouc are you sure ? Because I'm doing this, but it doesn't seems to work, because peerDependencies are still not on the same level.

```
    "@nivo/core": "0.65.1",
    "@nivo/bar": "0.65.1",
    "@nivo/funnel": "0.65.1",
    "@nivo/pie": "0.65.1",
    "@nivo/sankey": "0.65.1",
    "@nivo/stream": "0.65.1",
```

**Comment by wyze** [comment]
@arthuryeti In this case, there were no changes detected in `core` so it is still on `0.65.0` which is the same version the peerDependency is in the chart packages.

**Comment by arthuryeti** [comment]
Interesting, but the core has a peerDependencies on @nivo/tooltip 0.63.0. I'm using npm 7.

**Comment by arthuryeti** [comment]
@wyze I think the `core` should be updated, because right now it depends on `@nivo/tooltip@0.63.0` which break the `npm install`

**Comment by plouc** [comment]
@arthuryeti, you're right, we didn't consider this other peer dependency.

**Comment by plouc** [comment]
We might want to make the script a bit more generic @wyze.

**Comment by wyze** [comment]
Done in #1293.

**Comment by shakilmonsi** [comment]
Cannot find module '@nivo/line' or its corresponding type declarations.ts(2307)
No quick fixes available``` hey ervery body this  problem !! how to solve this

**Comment by plouc** [comment]
@shakilmonsi, I don't think everybody's having this issue since there was no activity for 5 years...
I have no idea what your setup is, if you want some help, please help the maintainers help you by providing a reproducible example, even the weird formatting shows that you're not willing to spend more that a minute to properly report an issue.
I'm a bit tired of these lazy comments with high expectations, this is ridiculous.
