### ISSUE TITLE
Custom tick and label formatter (Bar chart)

### ISSUE THREAD

**Issue by devmilind** [plouc/nivo#64]
Is there a way to format tick and label values? I noticed there is `sliceLabel` and `radialLabel` which can be a `function` in pie charts. Can we have a similar option for bar chart? The tick and label values I have is high 1000s. So I would like to display them with a `K` suffix. For example. `130K` instead of `130000` which it would display by default

**Comment by plouc** [comment]
Yes you can, for example:

```javascript
<Bar axisLeft={{ format: v => `${v}%` }} />
```

**Comment by SachaG** [comment]
That would be really helpful to have in the docs :)

**Comment by plouc** [comment]
@SachaG, you're right, the feature has been added without updating the documentation, but the website is now part, it should now be easier to align documentation with new features.
BTW, I'll add it.

**Comment by plouc** [comment]
Reopened until documentation reflect this feature.

**Comment by spredemann** [comment]
I still can't figure out how to format the tick values to be abbreviated numbers. The labelFormat=".0s" works fine but using a function for axisLeft format am I expected to use my own format implementation or can I tap into the same built in function?

**Comment by plouc** [comment]
@spredemann, you can use either custom function or d3-format specifier, you can see both in action [here](https://codesandbox.io/s/nrw0xpvw9j).

**Comment by spredemann** [comment]
@plouc thanks for the quick response. Very easy, don't know how I missed that. I was trying to return the d3-fromat specifier from the function, duh

**Comment by stahlmanDesign** [comment]
I tried `labelFormat` on a heatmap and it doesn't seem to be supported (it works on the axis). It seems `colorBy` is not supported either. Often I'd like to have a different label than the value used to colour it. For example, show `13/15` as the label but have the value be 13.

**Comment by stahlmanDesign** [comment]
In the line chart's dotLabelFormat I can't use `dotLabelFormat: '.0%'` because my data is already '12.0', not '0.12' %. So I used the function ```dotLabelFormat: v => `${v}%` ``` which works, but throws a prop types error because it expects a string.
``` Invalid prop `labelFormat` of type `function` supplied to `LineDots`, expected `string`.```

I'm sure a fix would be as simple as allowing a string OR function as accepted prop types.

**Comment by Stekot** [comment]
I have a same issue with `dotLabelFormat` expecting `string`. Also documentation on the site could be updated.

**Comment by gijsbotje** [comment]
@plouc i was trying to format the labels on my axes and found a few comments stating different formatting options. i tried all of them, but none of them worked. 
I found this codesandbox in one comment and it seems to work there
https://codesandbox.io/s/nrw0xpvw9j

But when i update all the dependencies.
https://codesandbox.io/s/rj40lrv76o

I've been trying to find where this is broken or if it's removed on purpose, but can't find an answer yet. 
I hope you have an answer for me or we could figure out why it's broken (or i'm doing things wrong)

**Comment by jcteague** [comment]
I'm seeing the same thing.  When I link directly from master instead of using published modules, the axis formatting worked.

**Comment by Hieropold** [comment]
I've tried the 0.51.0 version of @nivo/bar (which is the latest at the moment), but when I try to pass the format function it fails with the error that format is not a function. The same formatter function works with ResponsiveLine chart like a charm.

**Comment by plouc** [comment]
@gijsbotje @jcteague @Hieropold, see https://codesandbox.io/s/xp1yo2r76w, it works using `0.51.0`

**Comment by Hieropold** [comment]
@plouc Thanks, I've reinstalled all packages, checked everything again and found out that the problem was in my code. BarChart works as expected!

**Comment by jcteague** [comment]
I updated to 0.51 and it is working for me.

**Comment by BrunoQuaresma** [comment]
@plouc is it possible to use HTML elements on the format function?

**Comment by piltsen** [comment]
Is it possible to add an image inside the bar? PNG, JPG or even another SVG?

**Comment by plouc** [comment]
@piltsen, I've answered in the corresponding issue you created :)

**Comment by piltsen** [comment]
> @piltsen, I've answered in the corresponding issue you created :)

I will leave the link here in case someone else arrives here - [Adding image or SVG inside a bar](https://github.com/plouc/nivo/issues/582)

**Comment by sibelius** [comment]
can we format the label to be both the quantity and the percentage?

can we make labelFormat accept the whole datum point? so I can calculate the percentage of the point based on the whole dataset

**Comment by JacobMGEvans** [comment]
is it still not in the docs?
